const products = [
  {
    trackingNumber: "12345",
    trackingInfo: {
      origin: "New York",
      destination: "Los Angeles",
      weight: "10 kg",
      product: "Electronics",
      totalFreight: "$100",
      pickUpDate: new Date("2024-07-01"),
      comments: "Fragile item",
      packageQty: "1",
      carrier: "UPS",
      expectedDeliveryDate: new Date("2024-07-05"),
      pickUpTime: new Date("2024-07-01T10:00:00"),
      status: "In transit",
      typeOfShipment: "Express",
      carrierReferenceNo: "ABC123",
      paymentMode: "Credit card",
      departureTime: new Date("2024-07-01T12:00:00"),
    },
  },
  {
    trackingNumber: "23456",
    trackingInfo: {
      origin: "San Francisco",
      destination: "Seattle",
      weight: "8 kg",
      product: "Books",
      totalFreight: "$50",
      pickUpDate: new Date("2024-06-30"),
      comments: "Handle with care",
      packageQty: "3",
      carrier: "FedEx",
      expectedDeliveryDate: new Date("2024-07-03"),
      pickUpTime: new Date("2024-06-30T09:30:00"),
      status: "Delivered",
      typeOfShipment: "Standard",
      carrierReferenceNo: "DEF456",
      paymentMode: "Cash on delivery",
      departureTime: new Date("2024-06-30T11:00:00"),
    },
  },
  {
    trackingNumber: "34567",
    trackingInfo: {
      origin: "Chicago",
      destination: "Miami",
      weight: "15 kg",
      product: "Clothing",
      totalFreight: "$80",
      pickUpDate: new Date("2024-07-02"),
      comments: "No liquids",
      packageQty: "2",
      carrier: "USPS",
      expectedDeliveryDate: new Date("2024-07-06"),
      pickUpTime: new Date("2024-07-02T11:00:00"),
      status: "In warehouse",
      typeOfShipment: "Priority",
      carrierReferenceNo: "GHI789",
      paymentMode: "Bank transfer",
      departureTime: new Date("2024-07-02T13:30:00"),
    },
  },
  {
    trackingNumber: "45678",
    trackingInfo: {
      origin: "Dallas",
      destination: "Houston",
      weight: "12 kg",
      product: "Toys",
      totalFreight: "$70",
      pickUpDate: new Date("2024-07-01"),
      comments: "Handle with care",
      packageQty: "1",
      carrier: "DHL",
      expectedDeliveryDate: new Date("2024-07-04"),
      pickUpTime: new Date("2024-07-01T08:00:00"),
      status: "Out for delivery",
      typeOfShipment: "Express",
      carrierReferenceNo: "JKL012",
      paymentMode: "PayPal",
      departureTime: new Date("2024-07-01T10:30:00"),
    },
  },
  {
    trackingNumber: "56789",
    trackingInfo: {
      origin: "Seattle",
      destination: "Portland",
      weight: "5 kg",
      product: "Cosmetics",
      totalFreight: "$40",
      pickUpDate: new Date("2024-06-29"),
      comments: "Fragile items",
      packageQty: "2",
      carrier: "UPS",
      expectedDeliveryDate: new Date("2024-07-02"),
      pickUpTime: new Date("2024-06-29T10:30:00"),
      status: "Delayed",
      typeOfShipment: "Standard",
      carrierReferenceNo: "MNO345",
      paymentMode: "Credit card",
      departureTime: new Date("2024-06-29T12:00:00"),
    },
  },
];

export { products }
